version: "3.8"

services:
  superchat:
    image: aeolun/superchat:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6465:6465" # Must expose port for TCP protocol
    volumes:
      - superchat-data:/data
    restart: unless-stopped
    environment:
      - TZ=UTC

volumes:
  superchat-data:
    driver: local
