[package]
name = "binschema-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
json5 = "0.4.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[dev-dependencies]
tempfile = "3.14"

[lib]
name = "binschema_runtime"
path = "src/lib.rs"
